import { useState } from 'react';
import { prepareBankImport } from '@paymentplan/application';
import type { VaultSession, BankRow } from '@paymentplan/application';
import { live } from '@paymentplan/domain';
import type { Change } from '@paymentplan/domain';
import { readBankFile } from './bank-file.ts';
import type { Sheet } from './bank-file.ts';
import { Check, Dialog, SelectField, money, str } from './ui.tsx';
export function BankImport({ session, today, close, save }: { session: VaultSession; today: string; close: () => void; save: (changes: Change[]) => Promise<void> }) {
  const [sheets, setSheets] = useState<Sheet[]>([]), [selectedSheet, setSelectedSheet] = useState(0), [preview, setPreview] = useState<BankRow[]>([]);
  const [selected, setSelected] = useState<Set<number>>(new Set()), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const sheet = sheets[selectedSheet];
  const headings = sheet?.rows[0] ?? [];
  async function task(work: () => Promise<void>) { setBusy(true); setError(''); try { await work(); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo importar.'); } finally { setBusy(false); } }
  function column(name: string, label: string, optional = false) { return <SelectField key={name} name={name} label={label} value={optional ? '-1' : String(name === 'description' ? 1 : name === 'amount' ? 2 : 0)}>{optional && <option value="-1">Sin columna</option>}{headings.map((h, i) => <option key={i} value={i}>{i + 1} · {h || 'Sin título'}</option>)}</SelectField>; }
  return <Dialog title="Importar movimientos bancarios" close={close}><p className="caption">CSV o XLSX con encabezados. No se ejecutan fórmulas ni vínculos. Los importes se convierten a positivos y su tipo lo eliges tú; revisa pagos y gastos antes de confirmar.</p>
    <label className="file-button secondary">Seleccionar CSV / XLSX<input type="file" accept=".csv,.xlsx" disabled={busy} onChange={e => { const file = e.target.files?.[0]; void task(async () => { if (!file) return; setSheets(await readBankFile(file)); setSelectedSheet(0); setPreview([]); }); }} /></label>
    {sheets.length > 1 && <label className="field"><span>Hoja</span><select value={selectedSheet} onChange={e => { setSelectedSheet(Number(e.target.value)); setPreview([]); }}>{sheets.map((s, i) => <option value={i} key={i}>{s.name}</option>)}</select></label>}
    {sheet && !preview.length && <form key={selectedSheet} onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); void task(async () => {
      const result = await prepareBankImport(session.portfolio, str(d, 'card'), sheet.rows, { date: Number(str(d, 'date')), description: Number(str(d, 'description')), amount: Number(str(d, 'amount')), kind: Number(str(d, 'kind')), reference: Number(str(d, 'reference')), dateFormat: str(d, 'dateFormat') as 'iso' | 'dmy' | 'excel', decimalComma: d.has('decimalComma'), defaultKind: str(d, 'defaultKind') as 'expense' | 'payment' | 'fee' | 'interest' }, today);
      setPreview(result); setSelected(new Set(result.filter(r => !r.duplicate).map(r => r.row)));
    }); }}><div className="form-grid"><SelectField name="card" label="Tarjeta">{live(session.portfolio.cards).filter(c => !c.value.archived).map(c => <option key={c.id} value={c.id}>{c.value.name}</option>)}</SelectField>{column('date', 'Columna de fecha')}{column('description', 'Columna de descripción')}{column('amount', 'Columna de importe')}{column('kind', 'Columna de tipo', true)}{column('reference', 'Referencia única del banco', true)}
      <SelectField name="dateFormat" label="Formato de fecha"><option value="iso">Año-mes-día</option><option value="dmy">Día/mes/año</option><option value="excel">Fecha numérica de Excel (sistema 1900)</option></SelectField><SelectField name="defaultKind" label="Tipo si no hay columna"><option value="expense">Gasto</option><option value="payment">Pago</option><option value="fee">Comisión</option><option value="interest">Interés</option></SelectField><Check name="decimalComma" label="El importe usa coma decimal (1.234,56)" /></div><div className="dialog-actions"><button className="primary" disabled={busy}>Previsualizar movimientos</button></div></form>}
    {preview.length > 0 && <><p>{selected.size} movimientos seleccionados · {preview.filter(r => r.duplicate).length} ya registrados.</p><p className="caption">Si dos filas iguales no tienen referencia bancaria, se conservan como operaciones distintas. Una importación parcial de filas idénticas requiere revisión manual.</p><div className="table-wrap"><table><thead><tr><th>Importar</th><th>Fecha</th><th>Descripción</th><th>Tipo</th><th>Importe</th></tr></thead><tbody>{preview.map(r => <tr key={r.row}><td><input type="checkbox" aria-label={`Importar fila ${r.row}`} disabled={r.duplicate} checked={selected.has(r.row)} onChange={e => setSelected(s => { const next = new Set(s); if (e.target.checked) next.add(r.row); else next.delete(r.row); return next; })} />{r.duplicate && <small>Ya registrado</small>}</td><td>{r.date}</td><td>{r.description}</td><td>{({expense:'Gasto',payment:'Pago',fee:'Comisión',interest:'Interés'})[r.kind]}</td><td>{money(r.amountCents)}</td></tr>)}</tbody></table></div><div className="dialog-actions"><button className="secondary" onClick={() => setPreview([])}>Cambiar columnas</button><button className="primary" disabled={busy || !selected.size} onClick={() => void task(async () => { await save(preview.filter(r => selected.has(r.row) && r.change).map(r => r.change!)); close(); })}>Confirmar movimientos</button></div></>}
    {error && <p role="alert" className="alert error">{error}</p>}
  </Dialog>;
}
