import type { VaultSession } from '@paymentplan/application';
import type { FinancialIssue } from '@paymentplan/domain';
import { money } from './ui.tsx';
const names: Record<string, string> = { category:'Categoría',classification:'Clasificación',categoryRule:'Regla de categoría',categoryBudget:'Límite de categoría',recurrence:'Recurrencia',occurrence:'Propuesta recurrente',cashAccount:'Cuenta',cashEntry:'Movimiento de cuenta',savingsGoal:'Meta de ahorro',savingsEntry:'Reserva de meta', card: 'Tarjeta', balance: 'Saldo bancario', movement: 'Movimiento', installment: 'Plan a meses', statement: 'Corte', loan: 'Préstamo', loanPayment: 'Abono', income: 'Ingresos', budget: 'Presupuesto', reminderPreferences: 'Preferencias de avisos', reminderState: 'Aviso', closure: 'Cierre de periodo' };
const labels: Record<string, string> = { categoryId:'Categoría (ID)',movementId:'Movimiento (ID)',recurrenceId:'Recurrencia (ID)',accountId:'Cuenta (ID)',toAccountId:'Cuenta destino (ID)',cardMovementId:'Pago vinculado (ID)',goalId:'Meta (ID)',openingDate:'Fecha inicial',openingCents:'Saldo inicial',targetDate:'Fecha objetivo',limitCents:'Límite de categoría',frequency:'Frecuencia',endDate:'Última fecha',direction:'Reserva o liberación',contains:'Descripción contiene', name:'Nombre',bank:'Banco',description:'Descripción',person:'Persona',date:'Fecha',cutDate:'Corte',dueDate:'Fecha límite',payday:'Quincena',balanceDate:'Fecha del saldo',firstCutDate:'Primer corte',startDate:'Inicio',cutDay:'Día de corte',dueDay:'Día de pago',dueMonthOffset:'Meses después del corte',months:'Meses',kind:'Tipo',scheduled:'Programado',reconciled:'Conciliado',archived:'Archivado',initialDebtOrigin:'Origen de deuda',principalCents:'Capital',amountCents:'Importe',debtCents:'Deuda',availableCents:'Disponible',interestCents:'Intereses',targetCents:'Pago para no generar intereses',minimumCents:'Pago mínimo',initialPaidCents:'Ya pagado',reservedCents:'Apartado',income15Cents:'Ingreso del 15',incomeEndCents:'Ingreso de fin de mes',expensesCents:'Gastos',reserveCents:'Reserva',expectedIncomeCents:'Ingreso esperado',receivedIncomeCents:'Ingreso recibido',estimated:'Estimado',interestIncludedInDebt:'Interés ya incluido en deuda',interestIncorporatedThrough:'Intereses incorporados hasta',includeReceivedMoney:'Dinero recibido incluido en presupuesto',from:'Desde',to:'Hasta',closingDebtCents:'Deuda al cierre',closingAvailableCents:'Disponible al cierre',note:'Nota',color:'Color',enabled:'Avisos activos',daysBefore:'Anticipación',cuts:'Avisos de cortes',payments:'Avisos de pagos' };
const values: Record<string, string> = {payment:'Pago',expense:'Gasto',interest:'Interés',fee:'Comisión',currentPeriod:'Periodo en curso / próximo corte',previousStatement:'Corte anterior',unknown:'Por revisar'};
function RecordSummary({ value }: { value: unknown }) {
  if (!value) return <p className="caption">Esta versión anula el registro y conserva su historial.</p>;
  const record = value as Record<string, unknown>;
  return <div className="table-wrap"><table><tbody>{Object.entries(record).filter(([key]) => labels[key]).map(([key, item]) => <tr key={key}><th>{labels[key]}</th><td>{item === null ? 'Sin definir' : typeof item === 'boolean' ? item ? 'Sí' : 'No' : key.endsWith('Cents') ? money(item as number) : values[String(item)] ?? String(item)}</td></tr>)}</tbody></table>{Array.isArray(record.allocations) && record.allocations.length > 0 && <p className="caption">{record.allocations.map(a => `Cuota ${a.quotaNumber}: capital ${money(a.principalCents)}, interés ${money(a.interestCents)}`).join(' · ')}</p>}</div>;
}
export function ConflictReview({ session, today, issues, busy, perform }: { session: VaultSession; today: string; issues: readonly FinancialIssue[]; busy: boolean; perform: (work: () => Promise<void>) => void }) {
  return <section className="panel conflict-panel"><h2>Revisa cambios que necesitan tu decisión</h2><p className="caption">Tus registros están guardados. Compara las versiones y elige la correcta antes de seguir registrando movimientos.</p>
    {session.revisions.entities.filter(e => e.status === 'conflict').map(entity => <article key={entity.entityId}><h3>{names[entity.entityType] ?? 'Registro'} · dos versiones sin conexión</h3>{entity.heads.map((head, i) => <details key={head.operationId}><summary>Opción {i + 1}: {head.action === 'void' ? 'anular registro' : 'conservar esta versión'} · {new Date(head.updatedAt).toLocaleString('es-MX')}</summary><RecordSummary value={head.payload} /><button className="secondary" disabled={busy} onClick={() => perform(() => session.resolve(entity.entityId, head.operationId, today))}>Elegir opción {i + 1}</button></details>)}</article>)}
    {session.revisions.pendingOperationIds.length > 0 && <p className="alert">Faltan registros relacionados. Sincroniza o importa el respaldo completo antes de continuar.</p>}
    {issues.map((issue, index) => <details key={index}><summary>{issue.message}</summary>{issue.entityIds.map(id => {
      const entity = session.revisions.entities.find(e => e.entityId === id); if (!entity || entity.entityType === 'device') return null;
      const type = entity.entityType;
      return <article key={id}><h3>{names[type]}</h3><RecordSummary value={entity.accepted?.payload} /><div className="inline-actions">
        {['installment','loan'].includes(type) && <><button className="secondary" disabled={busy} onClick={() => perform(async () => { if (window.confirm('¿Confirmas que revisaste este registro junto con sus pagos y que los valores actuales son correctos?')) await session.acknowledgeForResolution(type, id, today); })}>Conservar tras revisión</button><button className="secondary" disabled={busy} onClick={() => perform(async () => { if (window.confirm('¿Restaurar los valores de la versión anterior de este registro? Se conservará todo el historial.')) await session.acknowledgeForResolution(type, id, today, true); })}>Revertir última edición</button></>}
        <button className="text-button danger" disabled={busy} onClick={() => perform(async () => { if (!window.confirm('¿Anular este registro para corregir la diferencia? Los saldos se recalcularán y se conservará el historial.')) return; await session.voidForResolution(type, id, today); })}>{type === 'closure' ? 'Reabrir este cierre' : 'Anular este registro'}</button></div></article>;
    })}</details>)}
  </section>;
}
