import { useState } from 'react';
import type { VaultSession } from '@paymentplan/application';
import { live, quotaBalances, suggestedPaymentDate } from '@paymentplan/domain';
import type { CardView, Change, FinanceView, Portfolio } from '@paymentplan/domain';
import { csvCell, Dialog, download, Empty, Icon, money, shortDate } from './ui.tsx';
import type { FinancialModal } from './financial-forms.tsx';
type Modal = (modal: FinancialModal) => void;
type Act = (prepare: () => Change[] | Promise<Change[]>) => void;
export function Dashboard({ view, modal, p }: { view: FinanceView; modal: Modal; p: Portfolio }) {
  const next = view.budgets.find(b => b.payday > view.today), current = view.budgets.filter(b => b.payday <= view.today).at(-1);
  const budget = current ?? next;
  return <><div className="metrics"><article><span>Deuda en tarjetas</span><strong>{money(view.debtCents)}</strong><small>{view.cards.length} tarjetas · saldo a favor {money(view.creditCents)}</small></article>
    <article><span>Préstamos a personas</span><strong>{money(view.loanDebtCents)}</strong><small>Sin intereses · sin fecha {money(view.undatedLoanDebtCents)}</small></article>
    <article className="highlight"><span>{budget ? `Quincena del ${shortDate(budget.payday)}` : 'Próxima quincena'}</span><strong>{money((budget?.pendingCents ?? 0) + (budget?.loanPendingCents ?? 0))}</strong><small>Tarjetas y préstamos por pagar{next && next !== budget ? ` · próxima ${money(next.pendingCents + next.loanPendingCents)}` : ''}</small></article></div>
    <section className="panel"><div className="section-heading"><h2>Tu plan vigente por tarjeta</h2><a href="#/plan">Ver todo el calendario →</a></div>
      {!view.cards.length ? <Empty title="Tu cartera empieza aquí" text="Registra el límite, disponible y deuda inicial de tus tarjetas. Después agrega gastos, pagos y planes a meses." action={<button className="primary" onClick={() => modal({ type: 'card' })}>Registrar mi primera tarjeta</button>} /> :
        <div className="table-wrap"><table><thead><tr><th>Tarjeta</th><th>Corte</th><th>Vencimiento</th><th>Ingreso para pagar</th><th className="numeric">Pendiente</th><th /></tr></thead><tbody>{view.cards.map(c => {
          const s = c.cuts.find(s => s.current)!;
          return <tr key={c.id}><td><strong>{c.name}</strong><small>{s.estimated ? 'Estimado' : 'Confirmado por ti'}</small></td><td>{shortDate(s.cutDate)}</td><td>{shortDate(s.dueDate)}</td><td>{shortDate(s.payday)}</td><td className="numeric">{money(s.pendingCents)}</td><td><button className="text-button" disabled={s.cutDate > view.today} onClick={() => modal({ type: 'cut', cardId: c.id, cut: s })}>Revisar corte</button></td></tr>;
        })}</tbody></table></div>}
      <p className="caption">Los estimados cambian con tus movimientos reales. El banco confirma el importe final y los cargos que aún no hayas registrado.</p></section>
    <section className="panel"><div className="section-heading"><h2>Por revisar</h2><a href="#/movimientos">Ver movimientos →</a></div>
      {view.cards.flatMap(c => c.alerts.map(a => <p className="alert" key={c.id + a.code}>{c.name}: {a.code === 'balanceMismatch' ? 'Disponible y deuda no cuadran con el límite' : a.code === 'limitExceeded' ? 'Se excedió el límite de crédito' : 'Tienes saldo a favor'} · {money(a.amountCents)}. Revisa los saldos con tu banco.</p>))}
      {view.cards.filter(c => c.reviewPreviousDebt).map(c => <p className="alert" key={c.id}>Revisa si la deuda inicial de {c.name} incluye un corte anterior. Registra ese corte para incluir su vencimiento.</p>)}
      {live(p.movements).filter(m => m.value.scheduled && m.value.date <= view.today).length > 0 && <p className="alert">Tienes movimientos programados cuya fecha ya llegó. Confírmalos solo si los realizaste.</p>}
      {!view.cards.some(c => c.alerts.length || c.reviewPreviousDebt) && !live(p.movements).some(m => m.value.scheduled && m.value.date <= view.today) && <p className="muted">Tus registros están al día. El sistema no realiza pagos bancarios automáticamente.</p>}</section></>;
}
function PlanDetails({ card, p, today, modal, act, session }: { card: CardView; p: Portfolio; today: string; modal: Modal; act: Act; session: VaultSession }) {
  const balances = quotaBalances(p, card.id, today);
  return <section className="card-detail"><div className="section-heading"><p className="caption">Deuda actual a meses: {money(card.installmentDebtCents)} · saldo libre para dividir: {money(card.freeDebtCents)}</p><button className="secondary" onClick={() => modal({ type: 'plan', cardId: card.id })}>Dividir deuda</button></div>
    {!card.plans.filter(r => !r.cancelled).length && <p className="muted">Esta tarjeta todavía no tiene planes a meses.</p>}
    <details className="plan-detail"><summary><strong>Resúmenes al corte</strong><span className="caption">{card.cuts.length} periodos registrados / estimados</span></summary><div className="table-wrap"><table><thead><tr><th>Corte</th><th>Vencimiento</th><th>Objetivo</th><th>Pagado</th><th>Apartado</th><th>Pendiente</th><th /></tr></thead><tbody>{card.cuts.map(c => <tr key={c.id}><td>{shortDate(c.cutDate)}<small>{c.estimated ? 'Estimado' : 'Confirmado'}</small></td><td>{shortDate(c.dueDate)}</td><td>{money(c.targetCents)}</td><td>{money(c.paidCents)}</td><td>{money(c.reservedCents)}</td><td>{money(c.pendingCents)}</td><td><button className="text-button" disabled={c.cutDate > today} onClick={() => modal({ type: 'cut', cardId: card.id, cut: c })}>Revisar</button></td></tr>)}</tbody></table></div></details>
    {card.plans.map(plan => <details className="plan-detail installment-detail" key={plan.id}><summary><span><strong>{plan.description}</strong><small>{plan.cancelled ? 'Cancelado · no genera obligaciones · ' : ''}{plan.months} cuotas · último pago {shortDate(plan.quotas.at(-1)!.dueDate)}</small></span><span className="numeric"><small>Saldo restante estimado</small><strong>{money(plan.remainingCents)}</strong></span></summary>
      <div className="plan-body"><div className="inline-actions"><span className="caption">Interés por devengar: {money(plan.futureInterestCents)}</span>{!plan.cancelled && <button className="text-button" onClick={() => modal({ type: 'plan', id: plan.id, cardId: card.id })}>Editar plan</button>}{!plan.cancelled && <button className="text-button danger" onClick={() => act(() => session.commands(today).cancelPlan(plan.id))}>Deshacer plan</button>}</div>
        {plan.editReason && <p className="caption">{plan.editReason}</p>}<div className="table-wrap"><table><thead><tr><th>Cuota</th><th>Corte / pago</th><th className="numeric">Capital</th><th className="numeric">Interés</th><th className="numeric">Saldo restante</th><th /></tr></thead><tbody>{plan.quotas.map(q => {
          const balance = balances.find(b => b.planId === plan.id && b.number === q.number);
          return <tr key={q.number}><td>{q.number}</td><td>{shortDate(q.cutDate)}<small>{shortDate(q.dueDate)}</small></td><td className="numeric">{money(q.principalCents)}</td><td className="numeric">{money(q.interestCents)}</td><td className="numeric">{money((balance?.principalCents ?? 0) + (balance?.interestCents ?? 0) + (balance?.futureInterestCents ?? 0))}</td><td>{!plan.cancelled && balance && balance.principalCents + balance.interestCents > 0 && <button className="text-button" onClick={() => modal({ type: 'movement', cardId: card.id, planId: plan.id, quotaNumber: q.number, capitalCents: balance.principalCents, interestCents: balance.interestCents })}>Pagar cuota</button>}</td></tr>;
        })}</tbody></table></div><p className="caption">El saldo restante incluye capital e intereses pendientes, también los futuros. Sin desglose bancario se estima la distribución de pagos; usa una atribución explícita para registrar anticipos a cuotas concretas.</p></div></details>)}</section>;
}
export function CardsView({ view, session, modal, act }: { view: FinanceView; session: VaultSession; modal: Modal; act: Act }) {
  const [selected, setSelected] = useState<string | null>(null), p = session.portfolio;
  const selectedCard = view.cards.find(c => c.id === selected);
  function openPlans(cardId: string) { setSelected(cardId); }
  function editFromPlans(next: FinancialModal) { setSelected(null); modal(next); }
  return <><div className="section-heading"><p className="muted">Ordenadas por mayor deuda · {view.cards.length} tarjetas</p><button className="primary" onClick={() => modal({ type: 'card' })}><Icon name="plus" size={16} /> Agregar tarjeta</button></div>
    {!view.cards.length && <Empty title="Registra tus tarjetas" text="Tus tarjetas tendrán sus propios saldos, color, corte y plan de pagos." />}
    <div className="credit-grid">{view.cards.map(c => {
      const data = p.cards.find(r => r.id === c.id)!.value, cut = c.cuts.find(s => s.current)!;
      return <article className="credit-card" key={c.id} style={{ '--card-color': data.color } as React.CSSProperties}><div className="credit-heading"><div><span>{data.bank}</span><h2>{c.name}</h2></div><details className="card-menu"><summary aria-label={`Acciones de ${c.name}`}>•••</summary><div>
        <button onClick={() => modal({ type: 'card', id: c.id })}>Editar tarjeta</button><button onClick={() => modal({ type: 'movement', cardId: c.id })}>Registrar movimiento</button><button onClick={() => modal({ type: 'plan', cardId: c.id })}>Dividir deuda / compra a meses</button>
        <button onClick={event => { event.currentTarget.closest('details')?.removeAttribute('open'); openPlans(c.id); }}>Ver planes</button><button onClick={() => modal({ type: 'reconcile', cardId: c.id })}>Conciliar con el banco</button><button disabled={cut.cutDate > view.today} onClick={() => modal({ type: 'cut', cardId: c.id, cut })}>Revisar corte</button><button onClick={() => modal({ type: 'cut', cardId: c.id, cut: { ...cut, cutDate: view.today, dueDate: view.today, targetCents: 0 }, create: true })}>Registrar otro corte</button><button onClick={() => modal({ type: 'reserve', cardId: c.id, cut })}>Apartar dinero para el corte</button>
        <button disabled={c.debtCents !== 0} onClick={() => act(() => session.commands(view.today).saveCard({ ...data, archived: true }, undefined, c.id))}>Archivar tarjeta liquidada</button><button className="danger" onClick={() => { if (window.confirm(`Eliminar ${c.name} y todo su historial de la cartera activa? Los registros cifrados se conservan anulados para sincronización.`)) act(() => session.commands(view.today).deleteCard(c.id)); }}>Eliminar tarjeta e historial</button></div></details></div>
        <div className="credit-chip" /><div className="credit-debt"><span>Deuda actual</span><strong>{money(Math.max(0, c.debtCents))}</strong></div>
        <div className="credit-balances"><div><span>Disponible</span><strong>{money(c.availableCents)}</strong></div><div><span>A meses</span><strong>{money(c.installmentDebtCents)}</strong></div></div>
        <div className="credit-limit"><span>Límite de crédito</span><strong>{money(data.limitCents)}</strong></div>
        <div className="credit-footer"><span>Corta {data.cutDay} · paga {data.dueDay}</span><button onClick={() => selected === c.id ? setSelected(null) : openPlans(c.id)}>Planes ({c.plans.filter(r => !r.cancelled).length}) →</button></div>
        {c.alerts.length > 0 && <span className="card-warning">{c.alerts.some(a => a.code !== 'creditBalance') ? 'Revisar cuadre de saldos' : 'Saldo a favor'}</span>}</article>;
    })}</div>
    {selectedCard && <Dialog title={`Planes de ${selectedCard.name}`} close={() => setSelected(null)} className="plans-dialog"><PlanDetails card={selectedCard} p={p} today={view.today} modal={editFromPlans} act={act} session={session} /></Dialog>}
    {live(p.cards).filter(c => c.value.archived).length > 0 && <details className="panel"><summary>Tarjetas archivadas</summary>{live(p.cards).filter(c => c.value.archived).map(c => <div className="settings-row" key={c.id}><span>{c.value.name}</span><button className="text-button" onClick={() => act(() => session.commands(view.today).saveCard({ ...c.value, archived: false }, undefined, c.id))}>Reactivar</button></div>)}</details>}</>;
}
export function MovementsView({ session, today, modal, act }: { session: VaultSession; today: string; modal: Modal; act: Act }) {
  const [filter, setFilter] = useState(''), [search, setSearch] = useState(''), [kindFilter, setKindFilter] = useState(''), [from, setFrom] = useState(''), [to, setTo] = useState(''), p = session.portfolio;
  const rows = p.movements.filter(m => live(p.cards).some(c => c.id === m.value.cardId) && (!kindFilter || m.value.kind === kindFilter) && (!from || m.value.date >= from) && (!to || m.value.date <= to) && (!filter || m.value.cardId === filter) && m.value.description.toLowerCase().includes(search.toLowerCase())).toSorted((a, b) => b.value.date.localeCompare(a.value.date) || (b.value.recordedAt ?? '').localeCompare(a.value.recordedAt ?? ''));
  const labels = { expense: 'Gasto', payment: 'Pago', interest: 'Interés', fee: 'Comisión' };
  return <section className="panel"><div className="filter-bar"><label>Tarjeta<select value={filter} onChange={e => setFilter(e.target.value)}><option value="">Todas las tarjetas</option>{live(p.cards).map(c => <option key={c.id} value={c.id}>{c.value.name}</option>)}</select></label><label>Buscar<input value={search} onChange={e => setSearch(e.target.value)} placeholder="Descripción del movimiento" /></label>
    <label>Tipo<select value={kindFilter} onChange={e => setKindFilter(e.target.value)}><option value="">Todos</option>{Object.entries(labels).map(([key, name]) => <option key={key} value={key}>{name}</option>)}</select></label><label>Desde<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Hasta<input type="date" min={from} value={to} onChange={e => setTo(e.target.value)} /></label><button className="secondary" onClick={() => download(`paymentplan-movimientos-${today}.csv`, '\ufeff' + [['Fecha', 'Tarjeta', 'Tipo', 'Descripción', 'MXN', 'Estado'], ...rows.map(m => [m.value.date, p.cards.find(c => c.id === m.value.cardId)?.value.name ?? '', labels[m.value.kind], m.value.description, (m.value.amountCents / 100).toFixed(2), m.voided ? 'Anulado' : m.value.scheduled ? 'Programado' : 'Realizado'])].map(row => row.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8')}>Exportar CSV</button></div>
    {!rows.length ? <Empty title="Cada movimiento cuenta" text="Usa Registrar movimiento en el encabezado para agregar gastos, pagos, comisiones o intereses." /> : <div className="table-wrap"><table><thead><tr><th>Fecha / tarjeta</th><th>Descripción</th><th>Tipo</th><th className="numeric">Importe</th><th>Estado</th><th>Acciones</th></tr></thead><tbody>{rows.map(m => <tr key={m.id} className={m.voided ? 'voided' : ''}><td>{shortDate(m.value.date)}<small>{p.cards.find(c => c.id === m.value.cardId)?.value.name}</small></td><td>{m.value.description}</td><td>{labels[m.value.kind]}</td><td className="numeric">{money(m.value.amountCents)}</td><td><span className="tag">{m.voided ? 'Anulado' : m.value.reconciled ? 'Conciliado' : m.value.scheduled || m.value.date > today ? 'Programado' : 'Realizado'}</span></td><td><div className="row-actions">
      {!m.voided && !m.value.reconciled && <button className="text-button" onClick={() => modal({ type: 'movement', id: m.id })}>Editar</button>}
      {!m.voided && (m.value.scheduled || m.value.date > today) && <button className="text-button" onClick={() => act(() => session.commands(today).changeMovement(m.id, 'realize'))}>Realizar</button>}
      {!m.value.reconciled && <button className="text-button" onClick={() => act(() => session.commands(today).changeMovement(m.id, m.voided ? 'restore' : 'void'))}>{m.voided ? 'Restaurar' : 'Anular'}</button>}
      {!m.voided && m.value.kind === 'payment' && <button className="text-button" onClick={() => modal({ type: 'allocation', id: m.id })}>Distribuir entre cuotas</button>}
      {!m.voided && m.value.kind === 'expense' && <button className="text-button" onClick={() => modal({ type: 'plan', cardId: m.value.cardId, purchaseId: m.id })}>Dividir a meses</button>}</div></td></tr>)}</tbody></table></div>}</section>;
}
export function CalendarView({ view, modal }: { view: FinanceView; modal: Modal }) {
  const [advance, setAdvance] = useState(() => { const saved = Number(localStorage.getItem('paymentplan-margin') ?? 2); return Number.isInteger(saved) && saved >= 0 && saved <= 10 ? saved : 2; });
  const rows = view.cards.flatMap(c => [...c.cuts.filter(s => s.current), ...c.projections].map(s => ({ ...s, name: c.name }))).sort((a, b) => a.payday.localeCompare(b.payday) || a.dueDate.localeCompare(b.dueDate));
  return <section className="panel"><p className="caption">Calendario hasta {shortDate(view.horizon)}. Las proyecciones suponen que pagas cada periodo completo antes del siguiente corte, sin nuevas compras ni cargos. Nunca registran pagos reales.</p>
    <label className="field"><span>Días de anticipación del pago</span><select value={advance} onChange={e => { const days = Number(e.target.value); setAdvance(days); localStorage.setItem('paymentplan-margin', String(days)); }}>{Array.from({length:11},(_,i)=><option key={i} value={i}>{i} días</option>)}</select><small>La sugerencia nunca precede el ingreso del 15 o fin de mes ni cambia la quincena asignada. Preferencia de este dispositivo.</small></label>
    <div className="table-wrap"><table><thead><tr><th>Quincena</th><th>Tarjeta</th><th>Corte</th><th>Vencimiento</th><th>Pago sugerido</th><th className="numeric">Por pagar</th><th>Origen</th></tr></thead><tbody>{rows.map((s, i) => <tr key={s.id + i}><td>{shortDate(s.payday)}</td><td>{s.name}</td><td>{shortDate(s.cutDate)}</td><td>{shortDate(s.dueDate)}</td><td>{shortDate(suggestedPaymentDate(s.dueDate,advance))}</td><td className="numeric">{money(s.pendingCents)}</td><td>{s.estimated ? s.current ? 'Estimado vigente' : 'Proyección' : 'Confirmado'}{s.current && s.cutDate <= view.today && <button className="text-button" onClick={() => modal({ type: 'cut', cardId: s.cardId, cut: s })}>Revisar</button>}</td></tr>)}</tbody></table></div>
    {view.obligations.length > 0 && <><h3>Compromisos con personas</h3><div className="table-wrap"><table><thead><tr><th>Quincena</th><th>Persona</th><th>Fecha de pago</th><th className="numeric">Por pagar</th></tr></thead><tbody>{view.obligations.map((o, i) => <tr key={i}><td>{shortDate(o.payday)}</td><td>{view.loans.find(l => l.id === o.loanId)?.person}</td><td>{shortDate(o.dueDate)}</td><td className="numeric">{money(o.amountCents)}</td></tr>)}</tbody></table></div></>}
    {!rows.length && !view.obligations.length && <p className="muted">Registra una tarjeta o un préstamo para construir tu calendario.</p>}</section>;
}
export function BudgetView({ view, modal, p }: { view: FinanceView; modal: Modal; p: Portfolio }) {
  const [past, setPast] = useState(false); const dates = view.budgets.filter(b => past || b.payday >= (view.budgets.filter(b => b.payday <= view.today).at(-1)?.payday ?? view.today));
  return <section className="panel"><div className="section-heading"><p className="caption">Todas las quincenas hasta {shortDate(view.horizon)}. Reserva = dinero que conservas para imprevistos.</p><label className="check"><input type="checkbox" checked={past} onChange={e => setPast(e.target.checked)} />Ver quincenas anteriores</label></div>
    <div className="table-wrap"><table><thead><tr><th>Ingreso</th><th className="numeric">Ingresos / préstamos</th><th className="numeric">Gastos / reserva</th><th className="numeric">Tarjetas</th><th className="numeric">Personas</th><th className="numeric">Balance</th><th /></tr></thead><tbody>{dates.map(b => <tr key={b.payday}><td>{shortDate(b.payday)}<small>{b.estimated ? 'Ingreso esperado / estimado' : 'Ingreso recibido'}</small></td><td className="numeric">{money(b.incomeCents + b.receivedLoanCents)}</td><td className="numeric">{money(b.expensesCents + b.reserveCents)}</td><td className="numeric">{money(b.pendingCents + b.cardPaidCents)}<small>Pendiente {money(b.pendingCents)}</small></td><td className="numeric">{money(b.loanPendingCents + b.loanPaidCents)}</td><td className={`numeric ${b.balanceCents < 0 ? 'negative' : ''}`}>{money(b.balanceCents)}</td><td><button className="text-button" onClick={() => modal({ type: 'budget', payday: b.payday })}>Editar</button><details><summary>Desglose</summary><p>Ingreso: {money(b.incomeCents)} · préstamos recibidos: {money(b.receivedLoanCents)}</p><p>Esenciales: {money(b.expensesCents)} · reserva: {money(b.reserveCents)}</p><p>Pagado a tarjetas: {money(b.cardPaidCents)} · a personas: {money(b.loanPaidCents)}</p>{view.cards.map(c => { const cuts = [...c.cuts.filter(s => s.current), ...c.projections].filter(s => s.payday === b.payday).toSorted((a,b) => b.cutDate.localeCompare(a.cutDate)); return cuts[0] && <p key={c.id}>{c.name}: {money(cuts[0].pendingCents)} pendiente · {cuts[0].estimated ? "estimado" : "confirmado"} · vence {shortDate(cuts[0].dueDate)}</p>; })}{view.obligations.filter(o => o.payday === b.payday).map((o,i) => <p key={i}>{view.loans.find(l => l.id === o.loanId)?.person}: {money(o.amountCents)} · vence {shortDate(o.dueDate)}</p>)}<p>{live(p.budgets).find(r => r.value.payday === b.payday)?.value.note}</p></details></td></tr>)}</tbody></table></div><a href="#/aprender">Entender reserva y presupuesto →</a></section>;
}
export function LoansView({ session, view, modal, act }: { session: VaultSession; view: FinanceView; modal: Modal; act: Act }) {
  const p = session.portfolio;
  return <><div className="section-heading"><p className="caption">Pago único y abonos sin intereses.</p><button className="primary" onClick={() => modal({ type: 'loan' })}><Icon name="plus" size={16} /> Registrar préstamo</button></div>
    {!view.loans.length && <Empty title="Préstamos de personas" text="Organiza a quién le debes, cuánto queda y cuándo acordaste pagar." />}
    <div className="loan-grid">{view.loans.map(l => { const value = p.loans.find(r => r.id === l.id)!.value; return <article className="panel" key={l.id}><div className="section-heading"><h2>{l.person}</h2><span className="tag">{value.archived ? 'Archivado' : l.balanceCents === 0 ? 'Liquidado' : value.dueDate && value.dueDate < view.today ? 'Vencido' : 'Pendiente'}</span></div>
      <p className="muted">{value.description}</p><div className="loan-balance"><small>Saldo pendiente</small><strong>{money(l.balanceCents)}</strong></div><p className="caption">{value.dueDate ? `Pago acordado: ${shortDate(value.dueDate)}` : 'Sin fecha acordada'} · programado {money(l.scheduledCents)}</p>
      <div className="inline-actions"><button className="secondary" disabled={value.archived || l.balanceCents <= l.scheduledCents} onClick={() => modal({ type: 'loanPayment', loanId: l.id })}>Registrar abono</button><button className="text-button" onClick={() => modal({ type: 'loan', id: l.id })}>Editar</button>{!p.loanPayments.some(a => a.value.loanId === l.id) && <button className="text-button danger" onClick={() => { if (window.confirm("Eliminar este préstamo sin abonos?")) act(() => session.commands(view.today).deleteLoan(l.id)); }}>Eliminar</button>}{l.balanceCents === 0 && <button className="text-button" onClick={() => act(() => session.commands(view.today).saveLoan({ ...value, archived: !value.archived }, l.id))}>{value.archived ? 'Reabrir' : 'Archivar'}</button>}</div>
      <details className="payment-history"><summary>Historial de abonos</summary>{p.loanPayments.filter(a => a.value.loanId === l.id).map(a => <div className="settings-row" key={a.id}><span>{shortDate(a.value.date)} · {a.value.description}<small>{money(a.value.amountCents)} · {a.voided ? 'Anulado' : a.value.scheduled || a.value.date > view.today ? 'Programado' : 'Realizado'}</small></span><div className="row-actions">{!a.voided && a.value.scheduled && <button className="text-button" onClick={() => act(() => session.commands(view.today).changeLoanPayment(a.id, 'realize'))}>Realizar</button>}<button className="text-button" onClick={() => act(() => session.commands(view.today).changeLoanPayment(a.id, a.voided ? 'restore' : 'void'))}>{a.voided ? 'Restaurar' : 'Anular'}</button></div></div>)}</details></article>; })}</div></>;
}
export { PeriodsView } from './period-views.tsx';
