import { useState } from 'react';
import { activityReport, live, simulatePayoff, sumCents } from '@paymentplan/domain';
import type { FinanceView, PayoffResult, Portfolio } from '@paymentplan/domain';
import { csvCell, download, Field, money, MoneyField, parseMoney, str } from './ui.tsx';

const banxico = 'https://contigo.banxico.org.mx/glosario.html';
const condusef = 'https://www.condusef.gob.mx/documentos/275553_Cr_dito.pdf';
const strategies = 'https://www.consumerfinance.gov/archive/blog/how-reduce-your-debt/';
const lessons = [
  { title: 'Elige el importe que realmente necesitas pagar', text: 'La deuda total y el pago para no generar intereses responden a preguntas diferentes. Compara el estimado del corte con el estado de cuenta y confírmalo o corrígelo. Cubrir solo el mínimo no equivale a cubrir ese objetivo.', question: '¿Qué importe usas para revisar el objetivo de una quincena?', options: ['El pago para no generar intereses del corte', 'Todo el capital de los meses futuros'], correct: 0, explanation: 'La app organiza el objetivo de cada corte; la deuda total también contiene compromisos futuros.', link: condusef, source: 'CONDUSEF · Crédito' },
  { title: 'Corte, vencimiento e ingreso', text: 'El corte reúne las operaciones del periodo; el vencimiento indica cuándo pagar. Aquí el ingreso del 15 cubre vencimientos del 15 al penúltimo día. El del último día cubre desde ese día hasta el 14 siguiente. Un corte puede vencer en el mes siguiente, como en tu configuración de Plata.', question: 'Si un pago vence el día 8, ¿qué ingreso lo cubre?', options: ['El 15 posterior', 'El último día del mes anterior'], correct: 1, explanation: 'Se usa el ingreso anterior al vencimiento, según la regla que definiste.', link: condusef, source: 'CONDUSEF · Crédito' },
  { title: 'Los meses siguen siendo deuda', text: 'En esta app el capital pendiente a meses forma parte de tu deuda y ocupa línea de crédito. Dividir una deuda la reclasifica; no crea otra compra. Una compra nueva a meses sí registra su gasto una sola vez. Los intereses futuros de MCI aparecen en el plan y se devengan según sus cortes.', question: '¿Dividir $6 000 de una deuda registrada agrega otros $6 000?', options: ['Sí', 'No, reclasifica el capital existente'], correct: 1, explanation: 'Revisa A meses, deuda libre y saldo restante para evitar financiar dos veces el mismo importe.', link: '#/tarjetas', source: 'Consultar mis planes' },
  { title: 'Reserva y dinero apartado', text: 'Reserva es dinero que conservas para imprevistos en tu presupuesto. Apartar dinero para un corte indica que ya lo tienes listo. Ninguna acción registra un pago ni reduce lo que debes. Registra el movimiento cuando pagues.', question: '¿Apartar dinero disminuye la deuda bancaria?', options: ['Sí, inmediatamente', 'No, hace falta registrar el pago real'], correct: 1, explanation: 'Así puedes distinguir dinero preparado y dinero ya pagado.', link: '#/presupuesto', source: 'Consultar mi presupuesto' },
  { title: 'Entiende el CAT antes de comparar', text: 'El CAT reúne componentes del costo de un crédito, incluyendo intereses y comisiones; excluye el IVA aplicable. No es la tasa mensual ordinaria. En una simulación captura la tasa mensual de tu contrato, nunca CAT dividido entre doce.', question: '¿Puedes usar CAT ÷ 12 como tasa mensual ordinaria?', options: ['No', 'Sí'], correct: 0, explanation: 'Son medidas diferentes. Comprueba qué tasa y cargos reporta tu banco.', link: banxico, source: 'Banco de México · CAT' },
  { title: 'Dos estrategias para reducir deudas', text: 'Avalancha prioriza la tasa más alta. Bola de nieve prioriza el saldo menor. Ambas mantienen los mínimos de las demás deudas y reasignan el dinero que se libera. La bola de nieve puede dar logros antes, pero también costar más intereses.', question: '¿Qué prioriza avalancha?', options: ['La tasa más alta', 'El saldo más pequeño'], correct: 0, explanation: 'Compara ambas estrategias con el mismo presupuesto en Simulador.', link: strategies, source: 'CFPB · Estrategias de deuda' },
  { title: 'Conciliar sin borrar tu historia', text: 'Si el banco reporta un saldo distinto, revisa fechas, cargos faltantes y planes antes de conciliar. La conciliación conserva los movimientos ya incorporados y evita sumarlos de nuevo. Confirmar un corte solo cambia el objetivo de pago; no sustituye los saldos de la tarjeta.', question: '¿Confirmar un corte reemplaza el saldo bancario?', options: ['Sí', 'No'], correct: 1, explanation: 'Usa Conciliar con el banco para saldos y Revisar corte para el importe a pagar.', link: '#/tarjetas', source: 'Revisar mis tarjetas' },
];
function Lesson({ lesson }: { lesson: typeof lessons[number] }) {
  const [choice, setChoice] = useState<number | null>(null);
  return <article className="panel lesson"><h2>{lesson.title}</h2><p>{lesson.text}</p><p><strong>{lesson.question}</strong></p><div className="row-actions">{lesson.options.map((option, i) => <button className="secondary" key={option} aria-pressed={choice === i} onClick={() => setChoice(i)}>{option}</button>)}</div>{choice !== null && <p role="status" className="form-note">{choice === lesson.correct ? 'Correcto. ' : 'Revisa esta idea. '}{lesson.explanation}</p>}<p><a href={lesson.link} {...(lesson.link.startsWith('https:') ? { target: '_blank', rel: 'noopener noreferrer' } : {})}>{lesson.source} ↗</a></p></article>;
}
export function EducationView({ view }: { view: FinanceView }) {
  const shortfall = view.budgets.find(b => b.payday >= view.today && b.balanceCents < 0);
  return <><section className="panel"><h2>Aprende usando tu cartera</h2><p>Lecciones breves y ejercicios disponibles sin conexión. Las fuentes externas necesitan internet. Tus respuestas permanecen en esta vista y no se envían a ningún servicio.</p>{shortfall && <p className="alert">Una quincena futura presenta un faltante de {money(-shortfall.balanceCents)}. Revisa el presupuesto antes de comprometer nuevos pagos.</p>}<a href="#/simulador">Comparar estrategias de pago →</a></section><div className="education-grid">{lessons.map(lesson => <Lesson key={lesson.title} lesson={lesson} />)}</div></>;
}
export function InsightsView({ p, today, view }: { p: Portfolio; today: string; view: FinanceView }) {
  const [from, setFrom] = useState(today.slice(0,8) + '01'), [to, setTo] = useState(today), [cardId, setCardId] = useState('');
  let rows: ReturnType<typeof activityReport> = [], error = '';
  try { rows = activityReport(p, from, to, today).filter(r => !cardId || r.cardId === cardId); } catch (e) { error = e instanceof Error ? e.message : 'Periodo inválido.'; }
  const expenses = sumCents(rows.map(r => r.expensesCents)), costs = sumCents(rows.flatMap(r => [r.feesCents, r.interestCents])), payments = sumCents(rows.map(r => r.paymentsCents));
  return <><section className="panel"><h2>Gastos y costo del crédito</h2><div className="filter-bar"><label>Desde<input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label>Hasta<input type="date" value={to} onChange={e => setTo(e.target.value)} /></label><label>Tarjeta<select value={cardId} onChange={e => setCardId(e.target.value)}><option value="">Todas</option>{live(p.cards).map(c => <option key={c.id} value={c.id}>{c.value.name}</option>)}</select></label></div>{error ? <p role="alert" className="alert">{error}</p> : <><div className="metrics compact"><article><span>Gastos realizados</span><strong>{money(expenses)}</strong></article><article><span>Intereses y comisiones</span><strong>{money(costs)}</strong></article><article><span>Pagos realizados</span><strong>{money(payments)}</strong></article></div><div className="table-wrap"><table><thead><tr><th>Tarjeta</th><th>Gastos</th><th>Comisiones</th><th>Intereses</th><th>Pagos</th></tr></thead><tbody>{rows.map(r => <tr key={r.cardId}><td>{r.name}</td><td>{money(r.expensesCents)}</td><td>{money(r.feesCents)}</td><td>{money(r.interestCents)}</td><td>{money(r.paymentsCents)}</td></tr>)}</tbody></table></div></>}<p className="caption">Incluye movimientos reales e intereses devengados de planes activos. Las compras a meses se cuentan una vez como gastos, no otra vez como cuotas. No se inventan cargos faltantes del banco ni se calcula rentabilidad.</p></section>
    <section className="panel"><h2>Uso actual de tu línea de crédito</h2>{view.cards.filter(c => !cardId || c.id === cardId).map(c => { const limit = p.cards.find(r => r.id === c.id)!.value.limitCents; const use = limit > 0 ? Math.max(0,c.debtCents) / limit * 100 : null; return <article key={c.id}><strong>{c.name}</strong><p>Deuda {money(c.debtCents)} · límite {money(limit)} · a meses {money(c.installmentDebtCents)} · {use === null ? 'Sin porcentaje: límite cero' : `uso ${use.toFixed(1)}%`}</p><div className="insight-bar" aria-hidden="true"><span style={{width: `${Math.min(100,use ?? 0)}%`}} /></div></article>; })}<p className="caption">Es una comparación de tus saldos registrados, no una calificación crediticia. El porcentaje puede exceder 100% y el banco puede reportar retenciones u otros ajustes.</p><a href="#/aprender">Entender el costo de mi crédito →</a></section></>;
}
export function PayoffView() {
  const [ids, setIds] = useState([1]), [results, setResults] = useState<PayoffResult[]>([]), [error, setError] = useState('');
  return <section className="panel"><h2>Compara avalancha y bola de nieve</h2><p className="caption">Escenario educativo mensual de deuda revolvente, separado de tus tarjetas y MSI/MCI. Usa tasa mensual nominal y mínimos fijos; no el CAT. Supone que no hay nuevas compras, comisiones, IVA ni cambios de tasa. El banco determina la aplicación real de anticipos.</p><form onSubmit={e => { e.preventDefault(); const data = new FormData(e.currentTarget); setError(''); setResults([]); try { const debts = ids.map(id => ({id: String(id), name: str(data, `name${id}`), balanceCents: parseMoney(data.get(`balance${id}`)), minimumCents: parseMoney(data.get(`minimum${id}`)), monthlyRate: str(data, `rate${id}`).replace(',', '.')})); const budget = parseMoney(data.get('budget')); setResults([simulatePayoff(debts,budget,'avalanche'),simulatePayoff(debts,budget,'snowball')]); } catch (e) { setError(e instanceof Error ? e.message : 'Revisa tus datos.'); } }}>
    <MoneyField label="Presupuesto mensual total para estas deudas" name="budget" value={null} hint="Incluye los mínimos y el importe adicional disponible cada mes." />
    {ids.map(id => <div className="form-grid payoff-debt" key={id}><Field label="Nombre de deuda" name={`name${id}`} /><MoneyField label="Saldo inicial" name={`balance${id}`} value={null} /><MoneyField label="Pago mínimo mensual fijo" name={`minimum${id}`} value={null} /><Field label="Tasa mensual nominal (%)" name={`rate${id}`} hint="Del contrato o estado de cuenta; hasta ocho decimales." />{ids.length > 1 && <button type="button" className="text-button" onClick={() => {setIds(list => list.filter(x => x!==id));setResults([]);}}>Quitar deuda</button>}</div>)}
    <div className="inline-actions"><button type="button" className="secondary" disabled={ids.length >= 50} onClick={() => {setIds(list => [...list, Math.max(...list)+1]);setResults([]);}}>Agregar deuda al escenario</button><button className="primary">Comparar estrategias</button></div></form>
    {error && <p role="alert" className="alert error">{error}</p>}{results.length > 0 && <><p className="caption">Resultado de los datos enviados. Si cambias un campo, vuelve a comparar.</p><div className="education-grid">{results.map(r => <article className="panel" key={r.strategy}><h3>{r.strategy === 'avalanche' ? 'Avalancha' : 'Bola de nieve'}</h3>{r.complete ? <p>Liquidación estimada: <strong>{r.schedule.length} meses</strong></p> : <p className="alert">{r.reason}</p>}<p>Interés {r.complete ? 'total' : 'hasta donde se calculó'}: <strong>{money(r.interestCents)}</strong> · pagado: {money(r.paidCents)}</p>{r.schedule.length > 0 && <><svg className="payoff-chart" viewBox="0 0 400 150" role="img" aria-label={`Saldo pendiente durante ${r.schedule.length} meses`}><polyline fill="none" stroke="var(--primary)" strokeWidth="3" points={r.schedule.map((m,i) => `${r.schedule.length===1?200:i*400/(r.schedule.length-1)},${145 - m.balanceCents / Math.max(...r.schedule.map(x=>x.balanceCents),1)*135}`).join(' ')} /></svg><details><summary>Tabla mensual y pagos por deuda</summary><div className="table-wrap"><table><thead><tr><th>Mes</th><th>Interés</th><th>Pagado</th><th>Saldo</th><th>Desglose por deuda</th></tr></thead><tbody>{r.schedule.map(m => <tr key={m.month}><td>{m.month}</td><td>{money(m.interestCents)}</td><td>{money(m.paidCents)}</td><td>{money(m.balanceCents)}</td><td>{m.debts.map(d => <small key={d.id}>{d.name}: pago {money(d.paidCents)}, saldo {money(d.balanceCents)}</small>)}</td></tr>)}</tbody></table></div></details><button className="text-button" onClick={() => download(`paymentplan-simulacion-${r.strategy}.csv`, '\ufeff' + [['Mes','Interés MXN','Pagado MXN','Saldo MXN',...r.schedule[0]!.debts.flatMap(d=>[d.name+' pago MXN',d.name+' saldo MXN'])],...r.schedule.map(m=>[m.month,(m.interestCents/100).toFixed(2),(m.paidCents/100).toFixed(2),(m.balanceCents/100).toFixed(2),...m.debts.flatMap(d=>[(d.paidCents/100).toFixed(2),(d.balanceCents/100).toFixed(2)])])].map(row=>row.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8')}>Exportar simulación CSV</button></>}</article>)}</div></>}
  </section>;
}
