import { useState } from 'react';
import type { VaultSession } from '@paymentplan/application';
import { activityReport, live, periodReport, sumCents } from '@paymentplan/domain';
import type { Change } from '@paymentplan/domain';
import type { Closure } from '@paymentplan/contracts';
import { csvCell, download, Field, money, MoneyField, optionalMoney, shortDate, str } from './ui.tsx';

type Act = (prepare: () => Change[] | Promise<Change[]>) => void;
function csv(name: string, rows: (string | number)[][]) { download(name, '\ufeff' + rows.map(r => r.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8'); }
function ClosureDetails({ value }: { value: Omit<Closure, 'historyHash' | 'recordedAt' | 'legacyOrdinal'> }) {
  return <div className="period-summary"><div className="metrics compact"><article><span>Deuda inicial</span><strong>{money(value.openingDebtCents)}</strong><small>Disponible {money(value.openingAvailableCents)}</small></article><article><span>Deuda final</span><strong>{money(value.closingDebtCents)}</strong><small>Disponible {money(value.closingAvailableCents)}</small></article></div>
    <p>Gastos {money(value.expensesCents)} · comisiones {money(value.feesCents)} · intereses {money(value.interestCents)} · pagos {money(value.paymentsCents)}</p>
    {value.bankDebtCents !== null && <p>Deuda bancaria {money(value.bankDebtCents)} · diferencia banco − sistema: {money(value.bankDebtCents - value.closingDebtCents)}</p>}
    {value.bankAvailableCents !== null && <p>Disponible bancario {money(value.bankAvailableCents)} · diferencia banco − sistema: {money(value.bankAvailableCents - value.closingAvailableCents)}</p>}
    <button className="text-button" onClick={() => csv(`paymentplan-cierre-${value.from}-${value.to}.csv`, [['Desde', 'Hasta', 'Deuda inicial MXN', 'Disponible inicial MXN', 'Pagos MXN', 'Gastos MXN', 'Comisiones MXN', 'Intereses MXN', 'Deuda final MXN', 'Disponible final MXN', 'Deuda bancaria MXN', 'Disponible bancario MXN'],
      [value.from, value.to, ...[value.openingDebtCents, value.openingAvailableCents, value.paymentsCents, value.expensesCents, value.feesCents, value.interestCents, value.closingDebtCents, value.closingAvailableCents].map(n => (n / 100).toFixed(2)), value.bankDebtCents === null ? '' : (value.bankDebtCents / 100).toFixed(2), value.bankAvailableCents === null ? '' : (value.bankAvailableCents / 100).toFixed(2)]] )}>Exportar cierre CSV</button></div>;
}
export function PeriodsView({ session, today, act }: { session: VaultSession; today: string; act: Act }) {
  const [range, setRange] = useState({ from: today.slice(0, 8) + '01', to: today }), [preview, setPreview] = useState<ReturnType<typeof periodReport> | null>(null), [error, setError] = useState('');
  let rows: ReturnType<typeof activityReport> = []; let activityError = '';
  try { rows = activityReport(session.portfolio, range.from, range.to, today); } catch (e) { activityError = e instanceof Error ? e.message : 'Periodo inválido.'; }
  return <><section className="panel"><h2>Actividad de todas las tarjetas</h2><p className="caption">No requiere un saldo histórico. Los movimientos programados se cuentan por separado; no se suman como gastos o pagos realizados. No incluye abonos a personas.</p>
    <div className="filter-bar"><label>Desde<input type="date" value={range.from} onChange={e => setRange(r => ({ ...r, from: e.target.value }))} /></label><label>Hasta<input type="date" value={range.to} onChange={e => setRange(r => ({ ...r, to: e.target.value }))} /></label><button className="secondary" disabled={!!activityError} onClick={() => csv(`paymentplan-actividad-${range.from}-${range.to}.csv`, [['Tarjeta', 'Pagos MXN', 'Gastos MXN', 'Comisiones MXN', 'Intereses MXN', 'Cambio deuda MXN', 'Realizados', 'Programados'], ...rows.map(r => [r.name, ...[r.paymentsCents, r.expensesCents, r.feesCents, r.interestCents, r.changeCents].map(n => (n / 100).toFixed(2)), r.realCount, r.plannedCount])])}>Exportar actividad CSV</button></div>
    {activityError ? <p className="alert error" role="alert">{activityError}</p> : <div className="table-wrap"><table><thead><tr><th>Tarjeta</th><th>Pagos</th><th>Gastos</th><th>Comisiones</th><th>Intereses</th><th>Cambio de deuda</th><th>Realizados / programados</th></tr></thead><tbody>{rows.map(r => <tr key={r.cardId}><td>{r.name}</td><td>{money(r.paymentsCents)}</td><td>{money(r.expensesCents)}</td><td>{money(r.feesCents)}</td><td>{money(r.interestCents)}</td><td>{money(r.changeCents)}</td><td>{r.realCount} / {r.plannedCount}</td></tr>)}</tbody><tfoot><tr><th>Total</th>{(['paymentsCents', 'expensesCents', 'feesCents', 'interestCents', 'changeCents'] as const).map(key => <td key={key}>{money(sumCents(rows.map(r => r[key])))}</td>)}<td>{rows.reduce((s,r) => s+r.realCount,0)} / {rows.reduce((s,r) => s+r.plannedCount,0)}</td></tr></tfoot></table></div>}</section>
    <section className="panel"><h2>Reconstruir y cerrar un periodo</h2><p className="caption">Necesita un saldo base conocido. Cerrar protege el historial hasta que lo reabras; puedes comparar el cierre con tu banco.</p><form onSubmit={event => { event.preventDefault(); setError(''); const d = new FormData(event.currentTarget); try { setPreview(periodReport(session.portfolio, str(d, 'cardId'), str(d, 'from'), str(d, 'to'), today)); } catch (e) { setPreview(null); setError(e instanceof Error ? e.message : 'Periodo inválido.'); } }}><div className="form-grid"><label className="field"><span>Tarjeta para cierre</span><select name="cardId">{live(session.portfolio.cards).map(c => <option key={c.id} value={c.id}>{c.value.name}</option>)}</select></label><Field label="Desde el saldo conocido" name="from" type="date" value={today} max={today} /><Field label="Hasta el cierre" name="to" type="date" value={today} max={today} /></div><button className="secondary">Ver resumen</button></form>
      {error && <p className="alert error" role="alert">{error}</p>}{preview && <><h3>{shortDate(preview.from)} — {shortDate(preview.to)}</h3><ClosureDetails value={{ ...preview, bankDebtCents: null, bankAvailableCents: null }} /><form onSubmit={e => { e.preventDefault(); const d = new FormData(e.currentTarget); act(() => session.commands(today).closePeriod(preview.cardId, preview.from, preview.to, optionalMoney(d, 'bankDebt', true), optionalMoney(d, 'bankAvailable'))); }}><div className="form-grid"><MoneyField label="Deuda bancaria al cierre (opcional, negativa si a favor)" name="bankDebt" required={false} value={null} /><MoneyField label="Disponible bancario al cierre (opcional)" name="bankAvailable" required={false} value={null} /></div><button className="secondary">Cerrar periodo</button></form></>}</section>
    <section className="panel"><h2>Periodos cerrados</h2>{live(session.portfolio.closures).map(c => <details className="plan-detail" key={c.id}><summary>{session.portfolio.cards.find(r => r.id === c.value.cardId)?.value.name} · {shortDate(c.value.from)} — {shortDate(c.value.to)}</summary><ClosureDetails value={c.value} /><button className="text-button" onClick={() => act(() => session.commands(today).reopenPeriod(c.id))}>Reabrir</button></details>)}{!live(session.portfolio.closures).length && <p className="muted">Aún no hay periodos cerrados.</p>}</section></>;
}
