import { useState } from 'react';
import type { VaultSession } from '@paymentplan/application';
import type { Change, FinancialEntityType, Portfolio } from '@paymentplan/domain';
import { addDays, addMonths, cashView, categorySpending, categorySuggestions, live, movementCategory, paydayFor, paydaysThrough, sumCents } from '@paymentplan/domain';
import { Check, Field, FormDialog, MoneyField, SelectField, csvCell, download, money, parseMoney, shortDate, str } from './ui.tsx';

type FormKind = 'category' | 'categoryRule' | 'categoryBudget' | 'classification' | 'recurrence' | 'cashAccount' | 'cashEntry' | 'savingsGoal' | 'savingsEntry';
type Editor = { type: FormKind; id?: string; related?: string };
type Props = { session: VaultSession; today: string; blocked: boolean; save: (changes: Change[]) => Promise<void> };
const kinds = { expense: 'Gasto', income: 'Ingreso', transfer: 'Transferencia', cardPayment: 'Pago a tarjeta', interest: 'Interés', fee: 'Comisión' };
export function PlanningView({ section, ...props }: Props & { section: 'categorias' | 'recurrencias' | 'cuentas' | 'metas' }) {
  const { session, today, blocked, save } = props, p = session.portfolio, [editor, setEditor] = useState<Editor | null>(null), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const [from, setFrom] = useState(today.slice(0, 8) + '01'), [to, setTo] = useState(today), [showArchived, setShowArchived] = useState(false), [through, setThrough] = useState(addMonths(today, 12));
  const cv = cashView(p, today), activeCategories = live(p.categories).filter(c => !c.value.archived), accounts = cv.accounts.filter(a => showArchived || !a.value.archived);
  async function perform(work: () => Change[] | Promise<Change[]>) { if (busy || blocked) return; setBusy(true); setError(''); try { await save(await work()); } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar.'); } finally { setBusy(false); } }
  const button = (label: string, type: FormKind, id?: string, related?: string) => <button className="secondary" disabled={blocked || busy} onClick={() => setEditor({ type, ...(id ? { id } : {}), ...(related ? { related } : {}) })}>{label}</button>;
  const archive = (type: 'category' | 'cashAccount' | 'savingsGoal', id: string) => {
    const c = session.commands(today);
    if (type === 'category') { const row = p.categories.find(r => r.id === id)!; return c.saveCategory({ ...row.value, archived: !row.value.archived }, id); }
    if (type === 'cashAccount') { const row = p.cashAccounts.find(r => r.id === id)!; return c.saveCashAccount({ ...row.value, archived: !row.value.archived }, id); }
    const row = p.savingsGoals.find(r => r.id === id)!; return c.saveSavingsGoal({ ...row.value, archived: !row.value.archived }, id);
  };
  const remove = (type: FinancialEntityType, id: string) => { if (window.confirm('¿Anular este registro? Se conservará su historial.')) void perform(() => session.commands(today).voidExtension(type, id)); };
  const archivedToggle = <label className="check"><input type="checkbox" checked={showArchived} onChange={e => setShowArchived(e.target.checked)} />Ver archivados</label>;
  const dateRange = <div className="filters"><label className="field"><span>Desde</span><input type="date" value={from} onChange={e => setFrom(e.target.value)} /></label><label className="field"><span>Hasta</span><input type="date" value={to} onChange={e => setTo(e.target.value)} /></label></div>;
  return <>{error && <p role="alert" className="alert error">{error}</p>}{blocked && <p className="alert">Resuelve las revisiones pendientes para modificar estos registros.</p>}
    {section === 'categorias' && <>
      <div className="section-heading"><p className="caption">Clasifica cargos sin modificar saldos ni cierres. Las reglas proponen; tú decides.</p>{button('Nueva categoría', 'category')}</div>
      <section className="panel">{dateRange}{archivedToggle}<div className="planning-grid">{live(p.categories).filter(c => showArchived || !c.value.archived).map(c => <article className="planning-card" key={c.id} style={{ borderTopColor: c.value.color }}><h2>{c.value.name}{c.value.archived && <small>Archivada</small>}</h2><strong className="planning-amount">{from && to && from <= to ? money(categorySpending(p, c.id, from, to, today)) : 'Revisa el intervalo'}</strong><small>Cargos registrados · crédito y cuentas</small><div className="inline-actions">{button('Editar', 'category', c.id)}<button className="text-button" disabled={blocked || busy} onClick={() => void perform(() => archive('category', c.id))}>{c.value.archived ? 'Reactivar' : 'Archivar'}</button></div></article>)}</div><p>Sin categoría: {from && to && from <= to ? money(categorySpending(p, null, from, to, today)) : '—'}. Los pagos y transferencias no se cuentan como nuevos gastos. Los intereses calculados de planes se consultan en Análisis.</p></section>
      <section className="panel"><div className="section-heading"><h2>Reglas por descripción</h2>{activeCategories.length > 0 && button('Nueva regla', 'categoryRule')}</div>{live(p.categoryRules).map(r => <div className="settings-row" key={r.id}><span><strong>{r.value.contains}</strong><small>{p.categories.find(c => c.id === r.value.categoryId)?.value.name} · {kinds[r.value.kind]} · {r.value.enabled ? 'Activa' : 'Pausada'} · {p.cards.find(c => c.id === r.value.cardId)?.value.name ?? 'Todas las tarjetas'}</small></span><div className="row-actions">{button('Editar', 'categoryRule', r.id)}<button className="text-button" disabled={blocked || busy} onClick={() => remove('categoryRule', r.id)}>Eliminar regla</button></div></div>)}</section>
      <section className="panel"><div className="section-heading"><h2>Límites por quincena</h2>{activeCategories.length > 0 && button('Nuevo límite', 'categoryBudget')}</div><p className="caption">Alertas de consumo; no se agregan otra vez a los gastos esenciales del presupuesto.</p>{live(p.categoryBudgets).toSorted((a,b) => b.value.payday.localeCompare(a.value.payday)).map(b => { const spent = categorySpending(p, b.value.categoryId, b.value.payday, addDays(paydaysThrough(addDays(b.value.payday, 1), addMonths(b.value.payday, 1))[0]!, -1), today); return <div className="settings-row" key={b.id}><span><strong>{p.categories.find(c => c.id === b.value.categoryId)?.value.name} · {shortDate(b.value.payday)}</strong><small className={spent > b.value.limitCents ? 'negative' : ''}>{money(spent)} de {money(b.value.limitCents)} {spent > b.value.limitCents ? '· Límite excedido' : '· Disponible ' + money(b.value.limitCents - spent)}</small></span><div className="row-actions">{button('Editar límite', 'categoryBudget', b.id)}<button className="text-button" disabled={blocked || busy} onClick={() => remove('categoryBudget', b.id)}>Eliminar</button></div></div>; })}</section>
      <section className="panel"><h2>Clasificar movimientos</h2><p className="caption">Las sugerencias coincidentes aparecen aquí, también para los movimientos importados. Si hay varias, elige la categoría correcta.</p><div className="table-wrap"><table><thead><tr><th>Fecha / cargo</th><th>Importe</th><th>Categoría / sugerencias</th><th /></tr></thead><tbody>{live(p.movements).filter(m => m.value.kind !== 'payment' && m.value.date >= from && m.value.date <= to).toSorted((a,b) => b.value.date.localeCompare(a.value.date)).map(m => { const cat = movementCategory(p, m.id), suggestions = cat ? [] : categorySuggestions(p, m.id); return <tr key={m.id}><td>{shortDate(m.value.date)}<small>{m.value.description} · {m.value.scheduled ? 'Propuesta' : 'Realizado'}</small></td><td>{money(m.value.amountCents)}</td><td>{p.categories.find(c => c.id === cat)?.value.name ?? 'Sin categoría'}<small>{suggestions.map(id => p.categories.find(c => c.id === id)?.value.name).join(' / ')}</small></td><td>{button('Clasificar', 'classification', m.id)}</td></tr>; })}</tbody></table></div></section>
    </>}
    {section === 'recurrencias' && <><div className="section-heading"><p className="caption">Suscripciones y cargos periódicos. Se generan propuestas, nunca cargos o pagos bancarios automáticos.</p>{live(p.cards).some(c => !c.value.archived) && button('Nueva recurrencia', 'recurrence')}</div><section className="panel"><div className="filters"><label className="field"><span>Preparar propuestas hasta</span><input type="date" value={through} onChange={e => setThrough(e.target.value)} /></label><button className="secondary" disabled={blocked || busy || !through} onClick={() => void perform(() => session.commands(today).prepareRecurrences(through))}>Preparar propuestas</button></div><p className="caption">Al desbloquear se preparan los próximos 12 meses. Una recurrencia con fecha final también puede prepararse hasta esa fecha. Editarla modifica las propuestas que aún no existen; las ya creadas se editan en Movimientos.</p>{live(p.recurrences).map(r => <div className="settings-row" key={r.id}><span><strong>{r.value.description}</strong><small>{p.cards.find(c => c.id === r.value.cardId)?.value.name} · {money(r.value.amountCents)} · {({ monthly: 'Mensual', weekly: 'Semanal', paydays: '15 y fin de mes' })[r.value.frequency]} · {r.value.enabled ? 'Activa' : 'Pausada'}</small><small>{shortDate(r.value.startDate)} → {r.value.endDate ? shortDate(r.value.endDate) : 'Sin fecha final'} · {p.occurrences.filter(o => !o.voided && o.value.recurrenceId === r.id).length} propuestas</small></span><div className="row-actions">{button('Editar', 'recurrence', r.id)}<button className="text-button" disabled={blocked || busy} onClick={() => void perform(() => session.commands(today).saveRecurrence({ ...r.value, enabled: !r.value.enabled }, r.id))}>{r.value.enabled ? 'Pausar' : 'Activar'}</button></div></div>)}</section><section className="panel"><h2>Propuestas por confirmar</h2>{live(p.occurrences).filter(o => p.movements.some(m => m.id === o.value.movementId && !m.voided && m.value.scheduled)).toSorted((a,b) => a.value.date.localeCompare(b.value.date)).map(o => { const m = p.movements.find(m => m.id === o.value.movementId)!; return <div className="settings-row" key={o.id}><span><strong>{m.value.description}</strong><small>{shortDate(o.value.date)} · {money(m.value.amountCents)}{o.value.date < today ? ' · Pendiente de confirmar' : ''}</small></span><div className="row-actions"><button className="secondary" disabled={blocked || busy || o.value.date > today} onClick={() => void perform(() => session.commands(today).changeMovement(m.id, 'realize'))}>Registrar como realizado</button><button className="text-button" disabled={blocked || busy} onClick={() => void perform(() => session.commands(today).changeMovement(m.id, 'void'))}>Omitir</button></div></div>; })}</section></>}
    {section === 'cuentas' && <><div className="section-heading"><p className="caption">Dinero real en efectivo y débito. El saldo se calcula con tus registros, sin conexión bancaria.</p>{button('Nueva cuenta', 'cashAccount')}</div><div className="summary-grid"><section className="stat-card"><small>Saldo total</small><strong>{money(cv.totalCents)}</strong></section><section className="stat-card"><small>Reservado en metas</small><strong>{money(cv.reservedCents)}</strong></section><section className="stat-card"><small>Libre para usar</small><strong>{money(cv.freeCents)}</strong></section></div>{archivedToggle}<div className="planning-grid">{accounts.map(a => <article className="panel" key={a.id} style={{ borderTop: '4px solid ' + a.value.color }}><h2>{a.value.name}<small>{a.value.kind === 'cash' ? 'Efectivo' : 'Débito'}{a.value.archived && ' · Archivada'}</small></h2><strong className="planning-amount">{money(a.balanceCents)}</strong><p className="caption">Libre {money(a.freeCents)} · metas {money(a.reservedCents)}</p><div className="inline-actions">{!a.value.archived && button('Registrar', 'cashEntry', undefined, a.id)}{button('Editar cuenta', 'cashAccount', a.id)}<button className="text-button" disabled={blocked || busy} onClick={() => void perform(() => archive('cashAccount', a.id))}>{a.value.archived ? 'Reactivar' : 'Archivar'}</button></div></article>)}</div><section className="panel"><div className="section-heading"><h2>Historial de cuentas</h2><button className="secondary" onClick={() => download('paymentplan-cuentas.csv', 'fecha,cuenta,tipo,importe,descripcion\n' + live(p.cashEntries).map(e => [e.value.date,p.cashAccounts.find(a => a.id === e.value.accountId)?.value.name ?? '',kinds[e.value.kind],(e.value.amountCents/100).toFixed(2),e.value.description].map(csvCell).join(',')).join('\n'), 'text/csv')}>Exportar CSV</button></div><p className="caption">Registra ingresos recibidos aquí aunque los hayas estimado en Preferencias. Al pagar una tarjeta desde esta sección se actualizan la cuenta y la tarjeta en un solo registro.</p>{dateRange}<div className="table-wrap"><table><thead><tr><th>Fecha</th><th>Cuenta / movimiento</th><th>Importe</th><th /></tr></thead><tbody>{p.cashEntries.filter(e => e.value.date >= from && e.value.date <= to).toSorted((a,b) => b.value.date.localeCompare(a.value.date)).map(e => <tr key={e.id}><td>{shortDate(e.value.date)}</td><td>{p.cashAccounts.find(a => a.id === e.value.accountId)?.value.name}<small>{kinds[e.value.kind]} · {e.value.description}{e.value.toAccountId && ' → ' + p.cashAccounts.find(a => a.id === e.value.toAccountId)?.value.name}{e.voided && ' · Anulado'}</small></td><td>{money(e.value.amountCents)}</td><td>{!e.voided && <div className="row-actions">{e.value.kind !== 'cardPayment' && button('Editar', 'cashEntry', e.id)}<button className="text-button" disabled={blocked || busy} onClick={() => remove('cashEntry', e.id)}>Anular</button></div>}</td></tr>)}</tbody></table></div></section></>}
    {section === 'metas' && <><div className="section-heading"><p className="caption">Aparta dinero existente de una cuenta. Reservar o liberar dinero no crea ingresos ni gastos.</p>{cv.accounts.some(a => !a.value.archived) && button('Nueva meta', 'savingsGoal')}</div>{archivedToggle}<div className="planning-grid">{cv.goals.filter(g => showArchived || !g.value.archived).map(g => <article className="panel" key={g.id} style={{ borderTop: '4px solid ' + g.value.color }}><h2>{g.value.name}<small>{p.cashAccounts.find(a => a.id === g.value.accountId)?.value.name}{g.value.archived && ' · Archivada'}</small></h2><strong className="planning-amount">{money(g.savedCents)} <small>de {money(g.value.targetCents)}</small></strong><progress aria-label={'Progreso de ' + g.value.name} value={Math.min(g.savedCents,g.value.targetCents)} max={g.value.targetCents} /><p className="caption">Falta {money(g.remainingCents)} · {g.value.targetDate ? 'objetivo ' + shortDate(g.value.targetDate) : 'Sin fecha objetivo'}</p>{g.remainingCents > 0 && g.value.targetDate && <p className={g.paydays.length ? 'caption' : 'negative'}>{g.paydays.length ? money(g.perPaydayCents) + ' por quincena · ' + g.paydays.length + ' quincenas' : 'No quedan quincenas antes del objetivo. Revisa la fecha.'}</p>}<div className="inline-actions">{!g.value.archived && button('Reservar / liberar', 'savingsEntry', undefined, g.id)}{button('Editar meta', 'savingsGoal', g.id)}<button className="text-button" disabled={blocked || busy} onClick={() => void perform(() => archive('savingsGoal', g.id))}>{g.value.archived ? 'Reactivar' : 'Archivar'}</button></div><details><summary>Historial de reservas</summary>{p.savingsEntries.filter(e => e.value.goalId === g.id).toSorted((a,b) => b.value.date.localeCompare(a.value.date)).map(e => <div className="settings-row" key={e.id}><span>{shortDate(e.value.date)} · {e.value.direction === 'allocate' ? 'Reservar' : 'Liberar'} {money(e.value.amountCents)}<small>{e.value.description}{e.voided && ' · Anulado'}</small></span>{!e.voided && <div className="row-actions">{button('Editar', 'savingsEntry', e.id)}<button className="text-button" disabled={blocked || busy} onClick={() => remove('savingsEntry', e.id)}>Anular</button></div>}</div>)}</details></article>)}</div><GoalBudget p={p} today={today} /></>}
    {editor && !blocked && <PlanningEditor key={JSON.stringify(editor)} {...props} editor={editor} close={() => setEditor(null)} />}
  </>;
}

export function GoalBudget({ p, today }: { p: Portfolio; today: string }) {
  const goals = cashView(p, today).goals.filter(g => !g.value.archived && g.value.targetDate !== null && g.remainingCents > 0);
  const end = goals.map(g => g.value.targetDate!).toSorted().at(-1);
  if (!end || end < today) return null;
  return <section className="panel"><h2>Ahorro sugerido por quincena</h2><p className="caption">Propuesta adicional hasta la última meta. Si tu reserva del presupuesto ya cubre este ahorro, no vuelvas a sumarlo. Solo reservarás dinero al registrarlo en Metas.</p><div className="table-wrap"><table><thead><tr><th>Quincena</th><th>Sugerido</th><th>Metas</th></tr></thead><tbody>{paydaysThrough(today, end).map(date => { const current = goals.filter(g => g.paydays.includes(date)); const sum = sumCents(current.map(g => g.perPaydayCents)); return <tr key={date}><td>{shortDate(date)}</td><td>{money(sum)}</td><td>{current.map(g => g.value.name).join(' · ')}</td></tr>; })}</tbody></table></div></section>;
}

function PlanningEditor({ session, today, save, editor, close }: Props & { editor: Editor; close: () => void }) {
  const p = session.portfolio, cmd = session.commands(today), [error, setError] = useState(''), [busy, setBusy] = useState(false);
  const table = { category: p.categories, categoryRule: p.categoryRules, categoryBudget: p.categoryBudgets, recurrence: p.recurrences, cashAccount: p.cashAccounts, cashEntry: p.cashEntries, savingsGoal: p.savingsGoals, savingsEntry: p.savingsEntries, classification: [] };
  const old = table[editor.type].find(r => r.id === editor.id)?.value as unknown as Record<string, string | number | boolean | null> | undefined;
  const v = (key: string, fallback = ''): string => String(old?.[key] ?? fallback), n = (key: string): number => Number(old?.[key] ?? 0);
  const [cashKind, setCashKind] = useState(v('kind', 'expense'));
  const categories = live(p.categories).filter(c => !c.value.archived || c.id === v('categoryId'));
  const category = (optional: boolean) => <SelectField label="Categoría" name="categoryId" value={editor.type === 'classification' ? movementCategory(p, editor.id!) ?? '' : v('categoryId')}><option value="">{optional ? 'Sin categoría' : 'Selecciona una categoría'}</option>{categories.map(c => <option key={c.id} value={c.id}>{c.value.name}</option>)}</SelectField>;
  const account = (name = 'accountId', label = 'Cuenta') => <SelectField label={label} name={name} value={v(name, editor.type === 'cashEntry' ? editor.related ?? '' : '')}><option value="">Selecciona una cuenta</option>{live(p.cashAccounts).filter(a => !a.value.archived || a.id === v(name)).map(a => <option key={a.id} value={a.id}>{a.value.name}</option>)}</SelectField>;
  const card = (optional = false) => <SelectField label="Tarjeta" name="cardId" value={v('cardId')}><option value="">{optional ? 'Todas las tarjetas' : 'Selecciona una tarjeta'}</option>{live(p.cards).filter(c => !c.value.archived).map(c => <option key={c.id} value={c.id}>{c.value.name}</option>)}</SelectField>;
  const color = <Field label="Color" name="color" type="color" value={v('color','#0F766E')} />;
  const name = <Field label="Nombre" name="name" value={v('name')} />;
  const description = <Field label="Descripción" name="description" value={v('description')} />;
  const date = <Field label="Fecha real" name="date" type="date" value={v('date',today)} max={today} />;
  const amount = <MoneyField label="Importe" name="amount" value={n('amountCents')} />;
  async function submit(d: FormData) {
    setBusy(true);setError(''); try {
      let changes: Change[];
      switch (editor.type) {
        case 'category': changes = cmd.saveCategory({ name: str(d,'name'), color: str(d,'color'), archived: Boolean(old?.archived) },editor.id);break;
        case 'classification': changes = await cmd.setCategory(editor.id!,str(d,'categoryId') || null);break;
        case 'categoryRule': changes = cmd.saveCategoryRule({ categoryId: str(d,'categoryId'), cardId: str(d,'cardId') || null, contains: str(d,'contains'), kind: str(d,'kind') as 'expense'|'interest'|'fee', enabled: d.has('enabled') },editor.id);break;
        case 'categoryBudget': changes = await cmd.saveCategoryBudget({ categoryId: str(d,'categoryId'), payday: str(d,'payday'), limitCents: parseMoney(d.get('limit')) });break;
        case 'recurrence': changes = cmd.saveRecurrence({ cardId:str(d,'cardId'), description:str(d,'description'), kind:str(d,'kind') as 'expense'|'interest'|'fee', amountCents:parseMoney(d.get('amount')), startDate:str(d,'start'), endDate:str(d,'end') || null, frequency:str(d,'frequency') as 'weekly'|'monthly'|'paydays', enabled:d.has('enabled'), categoryId:str(d,'categoryId') || null },editor.id);break;
        case 'cashAccount': changes = cmd.saveCashAccount({ name:str(d,'name'), kind:str(d,'kind') as 'cash'|'debit', openingDate:str(d,'openingDate'), openingCents:parseMoney(d.get('opening')), color:str(d,'color'), archived:Boolean(old?.archived) },editor.id);break;
        case 'cashEntry': {
          const kind = str(d,'kind') as 'income'|'expense'|'transfer'|'cardPayment';
          changes = kind === 'cardPayment' ? cmd.payCardFromAccount(str(d,'accountId'),str(d,'cardId'),str(d,'date'),parseMoney(d.get('amount')),str(d,'description')) : cmd.saveCashEntry({ accountId:str(d,'accountId'), toAccountId:kind === 'transfer' ? str(d,'toAccountId') : null, cardMovementId:null, date:str(d,'date'), amountCents:parseMoney(d.get('amount')), kind, description:str(d,'description'), categoryId:kind === 'expense' ? str(d,'categoryId') || null : null },editor.id); break;
        }
        case 'savingsGoal': changes = cmd.saveSavingsGoal({ accountId:str(d,'accountId'), name:str(d,'name'), targetCents:parseMoney(d.get('target')), targetDate:str(d,'targetDate') || null, color:str(d,'color'), archived:Boolean(old?.archived) },editor.id);break;
        case 'savingsEntry': changes = cmd.saveSavingsEntry({ goalId:editor.related ?? String(old?.goalId), date:str(d,'date'), amountCents:parseMoney(d.get('amount')), direction:str(d,'direction') as 'allocate'|'release', description:str(d,'description') },editor.id);break;
      }
      await save(changes); close();
    } catch (e) { setError(e instanceof Error ? e.message : 'No se pudo guardar.'); } finally { setBusy(false); }
  }
  const titles = { category:'Categoría',classification:'Clasificar movimiento',categoryRule:'Regla de categoría',categoryBudget:'Límite de categoría',recurrence:'Recurrencia',cashAccount:'Cuenta de efectivo / débito',cashEntry:'Movimiento de cuenta',savingsGoal:'Meta de ahorro',savingsEntry:'Reservar / liberar dinero' };
  return <FormDialog title={titles[editor.type]} close={close} submit={d => void submit(d)} error={error} busy={busy}>
    {editor.type === 'category' && <>{name}{color}</>}
    {editor.type === 'classification' && category(true)}
    {editor.type === 'categoryRule' && <>{category(false)}{card(true)}<Field label="La descripción contiene" name="contains" value={v('contains')} /><SelectField label="Tipo de cargo" name="kind" value={v('kind','expense')}><option value="expense">Compra</option><option value="interest">Interés</option><option value="fee">Comisión</option></SelectField><Check name="enabled" label="Regla activa" checked={old?.enabled !== false} /></>}
    {editor.type === 'categoryBudget' && <>{category(false)}<Field label="Quincena (15 o último día)" name="payday" type="date" value={v('payday',paydayFor(today))} /><MoneyField label="Límite de gastos" name="limit" value={n('limitCents')} /></>}
    {editor.type === 'recurrence' && <>{card()}{description}{amount}{category(true)}<SelectField label="Tipo de cargo" name="kind" value={v('kind','expense')}><option value="expense">Compra</option><option value="interest">Interés</option><option value="fee">Comisión</option></SelectField><SelectField label="Frecuencia" name="frequency" value={v('frequency','monthly')}><option value="monthly">Mensual</option><option value="weekly">Semanal</option><option value="paydays">15 y último día del mes</option></SelectField><Field label="Primera fecha" name="start" type="date" value={v('startDate',today)} /><Field label="Última fecha (opcional)" name="end" type="date" value={v('endDate')} required={false} /><Check name="enabled" label="Generar propuestas" checked={old?.enabled !== false} /></>}
    {editor.type === 'cashAccount' && <>{name}<SelectField label="Tipo de cuenta" name="kind" value={v('kind','debit')}><option value="debit">Débito</option><option value="cash">Efectivo</option></SelectField><Field label="Fecha del saldo inicial" name="openingDate" type="date" value={v('openingDate',today)} max={today} /><MoneyField label="Saldo inicial real" name="opening" value={n('openingCents')} />{color}</>}
    {editor.type === 'cashEntry' && <>{account()}<label className="field"><span>Tipo de movimiento</span><select name="kind" value={cashKind} onChange={e=>setCashKind(e.target.value)}><option value="expense">Gasto</option><option value="income">Ingreso recibido</option><option value="transfer">Transferir a otra cuenta</option>{!editor.id && <option value="cardPayment">Pagar tarjeta desde esta cuenta</option>}</select></label>{cashKind === 'transfer' && account('toAccountId','Cuenta destino')}{cashKind === 'cardPayment' && card()}{cashKind === 'expense' && category(true)}{date}{amount}{description}<p className="caption">Transferir mueve dinero entre cuentas. Pagar tarjeta reduce deuda y saldo de cuenta; no se cuenta como otro gasto.</p></>}
    {editor.type === 'savingsGoal' && <>{name}{account()}<MoneyField label="Objetivo" name="target" value={n('targetCents')} /><Field label="Fecha objetivo (opcional)" name="targetDate" type="date" value={v('targetDate')} required={false} />{color}</>}
    {editor.type === 'savingsEntry' && <><SelectField label="Acción" name="direction" value={v('direction','allocate')}><option value="allocate">Reservar dinero existente</option><option value="release">Liberar para usarlo</option></SelectField>{date}{amount}{description}<p className="caption">La cuenta conserva el mismo saldo total. La meta determina qué parte puedes usar.</p></>}
  </FormDialog>;
}
